plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android { namespace 'ro.alintudor.oracle'; compileSdk 35
    defaultConfig { applicationId 'ro.alintudor.oracle'; minSdk 26; targetSdk 35; versionCode 6; versionName '2.1.0' }
    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled false
        }
    }
}

kotlin { jvmToolchain(17) }
