from pathlib import Path

p=Path('app/src/main/java/ro/alintudor/oracle/core/OracleGrowthEngine.kt')
s=p.read_text(encoding='utf-8')

old='''        val universe=loadUniverse()\n        val candidates=java.util.concurrent.ConcurrentLinkedQueue<C>()\n        val deadline=System.nanoTime()+10_000_000_000L\n        val pool=java.util.concurrent.Executors.newFixedThreadPool(8)\n        try{universe.chunked(100).map{batch->pool.submit{val data=OracleMarketData.fetchDailyBatch(batch,"1y");for((ticker,candles) in data)if(System.nanoTime()<deadline&&candles.size>=60)evaluate(ticker,candles)?.let{candidates.add(it)}}}.forEach{f->runCatching{f.get(10,java.util.concurrent.TimeUnit.SECONDS)}}}finally{pool.shutdownNow()}\n        if(candidates.isEmpty())return emptyList()\n        val candidateList=candidates.toList()'''
new='''        val universe=loadUniverse()\n        val candidates=java.util.concurrent.ConcurrentLinkedQueue<C>()\n        val deadline=System.nanoTime()+10_000_000_000L\n        val pool=java.util.concurrent.Executors.newFixedThreadPool(12)\n        try{\n            val futures=universe.chunked(100).map{batch->pool.submit{\n                val data=OracleMarketData.fetchDailyBatch(batch,"1y")\n                for((ticker,candles) in data)if(System.nanoTime()<deadline&&candles.size>=60)evaluate(ticker,candles)?.let{candidates.add(it)}\n            }}\n            futures.forEach{f->val rem=deadline-System.nanoTime();if(rem>0)runCatching{f.get(rem,java.util.concurrent.TimeUnit.NANOSECONDS)}}\n        }finally{pool.shutdownNow()}\n        if(candidates.isEmpty())return emptyList()\n        val candidateList=candidates.toList()'''
if old not in s: raise SystemExit('batch block not found')
s=s.replace(old,new,1)

old2='''        val fundamentals=technicalShortlist.associate { c ->\n            c.ticker to runCatching { OracleRealData.fundamentals(c.ticker) }.getOrNull()\n        }\n        val sectorContexts=mutableMapOf<String,Double>()\n        val newsContexts=mutableMapOf<String,OracleNewsContext>()\n        for(c in technicalShortlist){\n            val f=fundamentals[c.ticker]\n            val sector=OracleRealData.resolvedSector(c.ticker,f?.sector)\n            if(sector != null && sector !in sectorContexts){\n                sectorContexts[sector]=runCatching { OracleRealData.sectorScore(OracleRealData.marketContext(sector)) }.getOrNull() ?: 50.0\n            }\n        }\n        val newsCandidates=technicalShortlist.take(15)\n        for(c in newsCandidates){\n            newsContexts[c.ticker]=runCatching { OracleRealData.newsContext(c.ticker) }.getOrDefault(OracleNewsContext(50,0,0,0,null))\n        }'''
new2='''        val enrichmentDeadline=System.nanoTime()+7_000_000_000L\n        val enrichPool=java.util.concurrent.Executors.newFixedThreadPool(12)\n        val fundamentalFutures=technicalShortlist.associate{c->c.ticker to enrichPool.submit<OracleFundamentals?>{runCatching{OracleRealData.fundamentals(c.ticker)}.getOrNull()}}\n        val fundamentals=mutableMapOf<String,OracleFundamentals?>()\n        fundamentalFutures.forEach{(ticker,f)->val rem=enrichmentDeadline-System.nanoTime();if(rem>0)runCatching{f.get(rem,java.util.concurrent.TimeUnit.NANOSECONDS)}.getOrNull()?.let{fundamentals[ticker]=it}}\n        val newsCandidates=technicalShortlist.take(10)\n        val newsFutures=newsCandidates.associate{c->c.ticker to enrichPool.submit<OracleNewsContext>{runCatching{OracleRealData.newsContext(c.ticker)}.getOrDefault(OracleNewsContext(50,0,0,0,null))}}\n        val newsContexts=mutableMapOf<String,OracleNewsContext>()\n        newsFutures.forEach{(ticker,f)->val rem=enrichmentDeadline-System.nanoTime();if(rem>0)runCatching{f.get(rem,java.util.concurrent.TimeUnit.NANOSECONDS)}.getOrNull()?.let{newsContexts[ticker]=it}}\n        enrichPool.shutdownNow()\n        val sectorContexts=mutableMapOf<String,Double>()\n        val sectors=technicalShortlist.mapNotNull{OracleRealData.resolvedSector(it.ticker,fundamentals[it.ticker]?.sector)}.distinct()\n        val sectorPool=java.util.concurrent.Executors.newFixedThreadPool(8)\n        val sectorFutures=sectors.associateWith{sector->sectorPool.submit<Double>{runCatching{OracleRealData.sectorScore(OracleRealData.marketContext(sector))}.getOrNull()?:50.0}}\n        sectorFutures.forEach{(sector,f)->runCatching{f.get(2,java.util.concurrent.TimeUnit.SECONDS)}.getOrNull()?.let{sectorContexts[sector]=it}}\n        sectorPool.shutdownNow()'''
if old2 not in s: raise SystemExit('enrichment block not found')
s=s.replace(old2,new2,1)

p.write_text(s,encoding='utf-8')
