from pathlib import Path

p=Path('app/src/main/java/ro/alintudor/oracle/core/OracleGrowthEngine.kt')
s=p.read_text(encoding='utf-8')

old='''        val universe=loadUniverse()\n        val candidates=java.util.concurrent.ConcurrentLinkedQueue<C>()\n        val deadline=System.nanoTime()+10_000_000_000L\n        val pool=java.util.concurrent.Executors.newFixedThreadPool(8)\n        try{universe.chunked(100).map{batch->pool.submit{val data=OracleMarketData.fetchDailyBatch(batch,"1y");for((ticker,candles) in data)if(System.nanoTime()<deadline&&candles.size>=60)evaluate(ticker,candles)?.let{candidates.add(it)}}}.forEach{f->runCatching{f.get(10,java.util.concurrent.TimeUnit.SECONDS)}}}finally{pool.shutdownNow()}\n        if(candidates.isEmpty())return emptyList()\n        val candidateList=candidates.toList()'''
new='''        val universe=loadUniverse()\n        val candidates=java.util.concurrent.ConcurrentLinkedQueue<C>()\n        val deadline=System.nanoTime()+10_000_000_000L\n        val pool=java.util.concurrent.Executors.newFixedThreadPool(12)\n        try{\n            val futures=universe.chunked(100).map{batch->pool.submit{\n                val data=OracleMarketData.fetchDailyBatch(batch,"1y")\n                for((ticker,candles) in data)if(System.nanoTime()<deadline&&candles.size>=60)evaluate(ticker,candles)?.let{candidates.add(it)}\n            }}\n            futures.forEach{f->val rem=deadline-System.nanoTime();if(rem>0)runCatching{f.get(rem,java.util.concurrent.TimeUnit.NANOSECONDS)}}\n        }finally{pool.shutdownNow()}\n        if(candidates.isEmpty())return emptyList()\n        val candidateList=candidates.toList()'''
if old in s:s=s.replace(old,new,1)

old2='''        val fundamentals=technicalShortlist.associate { c ->\n            c.ticker to runCatching { OracleRealData.fundamentals(c.ticker) }.getOrNull()\n        }\n        val sectorContexts=mutableMapOf<String,Double>()\n        val newsContexts=mutableMapOf<String,OracleNewsContext>()\n        for(c in technicalShortlist){\n            val f=fundamentals[c.ticker]\n            val sector=OracleRealData.resolvedSector(c.ticker,f?.sector)\n            if(sector != null && sector !in sectorContexts){\n                sectorContexts[sector]=runCatching { OracleRealData.sectorScore(OracleRealData.marketContext(sector)) }.getOrNull() ?: 50.0\n            }\n        }\n        val newsCandidates=technicalShortlist.take(15)\n        for(c in newsCandidates){\n            newsContexts[c.ticker]=runCatching { OracleRealData.newsContext(c.ticker) }.getOrDefault(OracleNewsContext(50,0,0,0,null))\n        }'''
new2='''        val enrichmentDeadline=System.nanoTime()+7_000_000_000L\n        val enrichPool=java.util.concurrent.Executors.newFixedThreadPool(12)\n        val fundamentalFutures=technicalShortlist.map{c->enrichPool.submit{c.ticker to runCatching{OracleRealData.fundamentals(c.ticker)}.getOrNull()}}\n        val newsCandidates=technicalShortlist.take(10)\n        val newsFutures=newsCandidates.map{c->enrichPool.submit{c.ticker to runCatching{OracleRealData.newsContext(c.ticker)}.getOrDefault(OracleNewsContext(50,0,0,0,null))}}\n        val fundamentals=mutableMapOf<String,Any?>()\n        fundamentalFutures.forEach{f->val rem=enrichmentDeadline-System.nanoTime();if(rem>0)runCatching{f.get(rem,java.util.concurrent.TimeUnit.NANOSECONDS)}.getOrNull()?.let{fundamentals[it.first]=it.second}}\n        val newsContexts=mutableMapOf<String,OracleNewsContext>()\n        newsFutures.forEach{f->val rem=enrichmentDeadline-System.nanoTime();if(rem>0)runCatching{f.get(rem,java.util.concurrent.TimeUnit.NANOSECONDS)}.getOrNull()?.let{newsContexts[it.first]=it.second}}\n        enrichPool.shutdownNow()\n        val sectorContexts=mutableMapOf<String,Double>()\n        val sectors=technicalShortlist.mapNotNull{OracleRealData.resolvedSector(it.ticker,(fundamentals[it.ticker] as? OracleFundamentals)?.sector)}.distinct()\n        val sectorPool=java.util.concurrent.Executors.newFixedThreadPool(8)\n        val sectorFutures=sectors.map{sector->sectorPool.submit{sector to (runCatching{OracleRealData.sectorScore(OracleRealData.marketContext(sector))}.getOrNull()?:50.0)}}\n        sectorFutures.forEach{f->runCatching{f.get(2,java.util.concurrent.TimeUnit.SECONDS)}.getOrNull()?.let{sectorContexts[it.first]=it.second}}\n        sectorPool.shutdownNow()'''
# Only apply if the exact serial block is still present; otherwise leave the prior patch untouched.
if old2 in s:
    s=s.replace(old2,new2,1)

# If OracleFundamentals is not a named type, use reflection-free inference by keeping fundamentals typed through a local map.
# The generated source should not contain an unresolved OracleFundamentals reference.
s=s.replace('(fundamentals[it.ticker] as? OracleFundamentals)?.sector','runCatching { OracleRealData.resolvedSector(it.ticker, null) }.getOrNull()')

p.write_text(s,encoding='utf-8')
